source 'http://rubygems.org'

gem 'rails', '3.2'
gem 'sqlite3'

gem 'best_in_place', :path => ".."

gem 'jquery-rails'

gem 'rdiscount'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
